### ISSUE TITLE
wtrSurf key not read from GRASP V1.12

### ISSUE THREAD

**Issue by ReedEspinosa** [ReedEspinosa/GSFC-GRASP-Python-Interface#9]
The `rslt` key `wtrSurf` is not appearing in Python when reading output from GRASP V1.12. The format of the headers in the text output likely has changed.

**Comment by ReedEspinosa** [comment]
It seems that this is just a results of us commenting out `retrieval.products.surface: True` in the most recent version of GRASP, since that particular YAML setting throws an error. The setting we actually know want is the following:
```
retrieval:
    products:
        surface:
            main_characteristics: true
```
